# ansible playbook to drive fabric policy
# start: 2020.06.24
# poomsawas@gmail.com
# modules: https://docs.ansible.com/ansible/latest/modules/list_of_network_modules.html
# good reference: https://github.com/datacenter/ansible-role-aci-model/blob/master/tasks/main-json.yml

- name: aci2 fabric policy
  hosts: irvsdc2-apic1
  connection: local
  gather_facts: no

  vars:
    aci_login: &aci_login
      hostname: "{{ apic_host }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      use_proxy: "{{ apic_use_proxy }}"
      validate_certs: "{{ apic_validate_certs }}"

  tasks:
  - name: populate node membership
    aci_fabric_node:
      <<: *aci_login
      state: "{{ item.state }}"
      name: "{{ item.name }}"
      serial: "{{ item.serial }}"
      pod_id: "{{ item.pod_id }}"
      node_id: "{{ item.node_id }}"
      role: "{{ item.role }}"
    with_items: "{{ fabric_policy.aci_fabric_node }}"

  - name: populate vpc protection group
    aci_switch_policy_vpc_protection_group:
      <<: *aci_login
      state: "{{ item.state }}"
      protection_group: "{{ item.protection_group }}"
      protection_group_id: "{{ item.protection_group_id }}"
      switch_1_id: "{{ item.switch_1_id }}"
      switch_2_id: "{{ item.switch_2_id }}"
    with_items: "{{ fabric_policy.vpc_protection_group }}"
